#pragma once
#define BACKGROUND_COLOR D3DCOLOR_XRGB(0, 0, 0)
#define SCREEN_WIDTH         320
#define SCREEN_HEIGHT        240

#define MAX_FRAME_RATE       120

#define ID_TEX_NINJA         0
#define ID_TEX_TILESET_31    1
#define ID_TEX_TILESET_32	 4
#define ID_TEX_MISC          20
#define ID_TEX_SOLDIER       10



#define PANTHER_BBOX_WIDTH     32 
#define PANTHER_BBOX_HEIGHT    16
#define PANTHER_STATE_WALKING   1 
#define PANTHER_ANI_WALKING     0
#define PANTHER_WALKING_SPEED   0.05f


#define NINJA_WALKING_RIGHT		0
#define NINJA_IDLE_RIGHT		1
#define NINJA_HIT_RIGHT         2
#define NINJA_ANI_JUMP			3
#define NINJA_SIT_RIGHT         4
#define NINJA_SIT_HIT			5
#define NINJA_ANI_FIGHT         6

#define NINJA_STATE_HIT            -5
#define NINJA_STATE_WALKING_RIGHT  -4
#define NINJA_STATE_WALKING_LEFT   -3
#define NINJA_STATE_DIE            -2
#define NINJA_STATE_IDLE            0
#define NINJA_STATE_JUMP            1
#define NINJA_STATE_SIT		        2
#define NINJA_STATE_

#define NINJA_STATE_HURT            3
#define NINJA_WALKING_SPEED         0.1f
#define NINJA_BBOX_WIDTH            20
#define NINJA_GRAVITY               0.002f
#define NINJA_JUMP_SPEED_Y		0.5f
#define NINJA_HITTING_TIME 300
#define NINJA_THROW_TIME 300

#define TROOPER_WALKING_SPEED   0.04f
#define TROOPER_GRAVITY         0.002f
#define TROOPER_BBOX_WIDTH      24
#define TROOPER_BBOX_HEIGHT		32
#define TROOPER_ANI				16001
#define TROOPER_STATE_HIT		100
#define TROOPER_STATE_RUN		200
#define TROOPER_ANI_RUN		0
#define TROOPER_ANI_HIT    1


#define ZOOMBIE_WALKING_SPEED 0.04f
#define ZOOMBIE_GRAVITY 0.002f
#define ZOOMBIE_BBOX_WIDTH 16
#define ZOOMBIE_BBOX_HEIGHT 43
#define ZOOMBIE_BBOX_HEIGHT_DIE 9
#define ZOOMBIE_STATE_HIT 100
#define ZOOMBIE_STATE_RUN 200
#define ZOOMBIE_ANI_HIT 1
#define ZOOMBIE_ANI_RUN 0


#define ITEM_SPIRIT_POINTS_BLU   90001
#define ITEM_SPIRIT_POINTS_RED   90002

#define ITEM_BONUS_POINTS_BLUE	 90009
#define ITEM_BONUS_POINT_RED	 90010
#define ITEM_HEALTH_BLU          90011
#define ITEM_HEALTH_RED          90012
#define ITEM_TIME_FREEZE	     90018
#define ITEM_EXTRA_LIFE        	 90008

#define ITEM_THROWING_STAR       90003
#define ITEM_WINDMILL_STAR       90004
#define ITEM_JUMP_AND_SLASH  	 90005
#define ITEM_FLAMES	             90006
#define ITEM_FIRE_WHEEL     	 90007

#define ITEM_ENERGY  90019

#define BUTTERFLY_BBOX_WIDTH     15
#define BUTTERFLY_BBOX_HEIGHT    15
#define BUTTERFLY_ANI_RIGHT     0
#define BUTTERFLY_WALKING_SPEED   0

#define EAGLE_BBOX_WIDTH     15
#define EAGLE_BBOX_HEIGHT    15

#define EAGLE_ANI_RIGHT     0
#define EAGLE_ANI_1         0
#define EAGLE_ANI_2			1
#define EAGLE_FLY_SPEED   0.05f


#define SOLDIER_WALKING_SPEED 0.05f
#define SOLDIER_GRAVITY 0.002f
#define SOLDIER_BBOX_WIDTH 24
#define SOLDIER_BBOX_HEIGHT 40
#define SOLDIER_BBOX_HEIGHT_DIE 9
#define SOLDIER_STATE_WALKING 100
#define SOLDIER_STATE_DIE 200
#define SOLDIER_ANI_WALKING 0
#define SOLDIER_ANI_DIE 1

#define TROOPER_SWORD_ANI_HIT 0
#define TROOPER_SWORD_BBOX_HEIGHT 3
#define TROOPER_SWORD_BBOX_WIDTH  8

#define ZOOMBIE_SWORD_ANI_HIT 0
#define ZOOMBIE_SWORD_BBOX_HEIGHT 15
#define ZOOMBIE_SWORD_BBOX_WIDTH  8
#define ZOOMBIE_BBOX_WIDTH 20

#define BRICK_BBOX_WIDTH  16
#define BRICK_BBOX_HEIGHT 16

#define ID_ANI_EFFECT 11001
